#include "Arlo.h"

void setup() {
  Serial.begin(9600);
  while(!Serial);
  Serial.println("Hello, world!");
  Arlo::proto(9, 8, 6, 7, A0); //AHHHHHHHH IT SEEMS LIKE THE CAPACITIVE SENSOR DIOGNOSTIC IS BURNING OUT PINS
  //IT SEEMS LIKE SOME COMBINATIONS OF PINS 8, 9, 10, AND OR 11 HAVE BEEN AFFECTED
  //CHECK TO MAKE SURE THAT THE AUTOMATIC BUS SETTINGS ARE RIGHT, USE CHATGPT AND NOT CLAUDE
  //ALSO TRY MANUAL MODE OR ADDING A DELAY BETWEEN DIGITAL LOGIC OPERATIONS
}

void loop() {
  Arlo::orbit();
}
